name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput dist
    - name: Archive release
      uses: actions/upload-artifact@v3
      with:
        name: lombok-release
        path: dist/lombok.jar
